export enum MessageType {
  SCREEN_OK = 'SCREEN_OK',
  JOIN_OK = 'JOIN_OK',
  USERNAME_TAKEN = 'USERNAME_TAKEN',
  LOBBY_STATE = 'LOBBY_STATE',
  GAME_START = 'GAME_START',
  ERROR = 'ERROR',
  QUESTION = 'QUESTION',
  ROUND_RESULT = 'ROUND_RESULT',
  CONNECT = 'CONNECT',
  ANSWER = 'ANSWER',
  GAME_END = 'GAME_END',
  NEXT_QUESTION = 'NEXT_QUESTION',
}
